### ISSUE TITLE
Is multiple values / datasources confirmed working?

### ISSUE THREAD

**Issue by bluecmd** [kimor79/gollectd#2]
Hi,

First: Awesome work getting a native entry-point for CollectD!

I'm trying to connect my collectd setup to my InfluxDB test environment, and things seems to be working somewhat. The odd thing is that I'm seeing triple inserts for the same value/dsname:
1415750557      263910001               longterm        gauge   0.05    REDACTED        load            load
1415750557      263900001               longterm        gauge   0.05    REDACTED        load            load
1415750557      263890001               longterm        gauge   0.05    REDACTED        load            load
1415750547      262140001               longterm        gauge   0.05    REDACTED        load            load
1415750547      262130001               longterm        gauge   0.05    REDACTED        load            load
1415750547      262120001               longterm        gauge   0.05    REDACTED        load            load
1415750537      260370001               longterm        gauge   0.05    REDACTED        load            load
1415750537      260360001               longterm        gauge   0.05    REDACTED        load            load

I couldn't see that you're actually testing the output of Values in gollectd_test, so this might be something that slipped through. Anyway, let me know if you need more info and I'll be happy to provide you with it.

**Comment by kimor79** [comment]
influxdb v0.8.8 handles multiple values correctly and v0.9.0 stores everything as tags.
